name: pangenome
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.1
  - r-base==3.5.1
  - snakemake==5.30.1
  - pybedtools
  - flask==1.1.2
  - pypdf2==1.26.0
  - markdown==3.0.1
  - r-ape
  - r-optparse
  - r-tidyverse
  - gatk4==4.1.9.0
  - samtools==1.10
  - seqkit
  - graphaligner==1.0.12
  - mash
  - repeatmasker==4.1.1
  - diamond
  - hisat2
  - augustus==3.3.3
  - stringtie==2.1.1
  - vt
  - bcftools
  - bwa
  - samblaster
  - fastp
  - bioconductor-edger    
